akamai/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.http import HttpResponseRedirect, HttpResponse

urlpatterns = [
	url(r'^$', lambda x: HttpResponseRedirect('/ssllabs/')),
    url(r'^ssllabs/', include('ssllabs.urls', namespace="ssllabs")),
    url(r'^admin/', include(admin.site.urls)),

    #Robots
    url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain"))
]

ssllabs/urls.py
from django.conf.urls import url
from . import views
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

urlpatterns = [

    #Auth and logout
    url(r'^auth/$', views.auth, name='auth'),
    url(r'^logout/$', views.logout_view, name='logout_view'),

    #Management
	url(r'^manage/$', login_required(views.IndexView.as_view()), name='listhosts'),
    url(r'^manage/(?P<host_id>[0-9]+)/$', views.managehost, name='managehost'),
    url(r'^manage/add/$', views.managehost, name='managehost'),
    url(r'^manage/scan/(?P<host_id>[0-9]+)/$', views.scanhost, name='scanhost'),
    url(r'^manage/delete/(?P<host_id>[0-9]+)/$', views.deletehost, name='deletehost'),

    #Dashboard
    url(r'^$', views.dashboard, name='dashboard'),

]

ssllabs/models.py
from django.db import models

class Account(models.Model):
	account_id = models.AutoField(primary_key=True)
	name = models.CharField(max_length=100, unique=True)
	def __str__(self):
			return self.name

class Host(models.Model):

	host_id = models.AutoField(primary_key=True)
	account_id = models.ForeignKey(Account)
	host = models.CharField(max_length=100, unique=True)
	port = models.IntegerField(default=443)
	status = models.CharField(max_length=20, null=True)
	statusMessage = models.CharField(max_length=100, null=True)
	startTime = models.DateTimeField('Start Time',null=True, blank=True)
	endTime = models.DateTimeField('End Time', null=True, blank=True)
	notBefore = models.DateTimeField('Not Before', null=True, blank=True)
	notAfter = models.DateTimeField('Not After', null=True, blank=True)
	ipAddress = models.GenericIPAddressField(null=True, blank=True)
	grade = models.CharField(max_length=3, null=True, blank=True)
	gradeTrustIgnored = models.CharField(max_length=3, null=True, blank=True)
	signatureAlg = models.CharField(max_length=20, null=True, blank=True)
	supportsRC4 = models.CharField(max_length=10, null=True, blank=True)
	def __str__(self):
			return self.host;

class Profile(models.Model):
	profileId = models.AutoField(primary_key=True)
	profileName = models.CharField(max_length=20, unique=True)
	lastModified = models.DateTimeField('Last Modified')
	def __str__(self):
			return self.profileName

class ProfileHosts(models.Model):
	profileId = models.ForeignKey(Profile)
	host = models.ForeignKey(Host)

ssllabs/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib import messages
from django.db import models, Error, IntegrityError
from django.db.models import Count, Max
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings
from django.contrib.messages import get_messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

from .models import Host, Account, Profile

import socket
import csv

#def index(request):
#	host_list = Host.objects.order_by('host')
#	context = {'host_list': host_list}
#	return render(request, 'ssllabs/index.html', context)


#def hosts(request, host_id):
#	host_detail = get_object_or_404(Host, pk=host_id);
#	context = {'host_detail': host_detail}
#	return render(request, 'ssllabs/hosts.html', context)

def logout_view(request):
	logout(request)
	return HttpResponseRedirect(reverse('ssllabs:auth'))

def auth(request):

	if request.POST:
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect(reverse('ssllabs:dashboard'))
			else:
				# Return a 'disabled account' error message
				error = "Account is disabled"

		else:
			error = "Invalid username and/or password"

		context = {'error' : error}
	else:
		context = {}

	return render(request, 'ssllabs/auth.html', context)

@login_required
def dashboard(request):

	account_name = 'All Accounts'
	selected_account_id = request.GET.get('select_account')
	selected_grade = ''
	selected_sig = ''
	selected_rc4 = ''
	
	if selected_account_id:
		kwargs = {}
		selected_account_id = request.GET.get('select_account')
		selected_grade = request.GET.get('grade_filter')
		selected_sig = request.GET.get('sig_filter')
		selected_rc4 = request.GET.get('rc4_filter')

		if selected_account_id != '0':
			kwargs['account_id'] = selected_account_id
			account_name = get_object_or_404(Account, pk=selected_account_id)
		if selected_grade != '':
			kwargs['grade'] = selected_grade
		if selected_sig != '':
			kwargs['signatureAlg'] = selected_sig
		if selected_rc4 != '':
			kwargs['supportsRC4'] = selected_rc4
	else:
		kwargs = {}
		selected_account_id='0'

	h_all = Host.objects.all().filter(**kwargs).order_by('account_id__name', 'host')

	#Export to csv
	if request.GET.get('exportCSV') == 'true':
		return export_to_csv(request, h_all)

	q_grade = Host.objects.all().values('grade').annotate(num_hosts=Count('host')).filter(**kwargs).order_by('grade')
	q_sig_alg = Host.objects.all().values('signatureAlg').annotate(num_hosts=Count('host')).filter(**kwargs).order_by('signatureAlg')
	q_rc4 = Host.objects.all().values('supportsRC4').annotate(num_hosts=Count('host')).filter(**kwargs).order_by('supportsRC4')
	a_all = Account.objects.all().order_by('name')
	q_last_update = Host.objects.all().aggregate(last_update=Max('endTime'))

	last_update = q_last_update['last_update']

	h_all_paginator = Paginator(h_all, settings.PAGE_SIZE)
	page = request.GET.get('page')

	try:
		hosts = h_all_paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		hosts = h_all_paginator.page(1)
	except EmptyPage:
	# If page is out of range (e.g. 9999), deliver last page of results.
		hosts = h_all_paginator.page(h_all_paginator.num_pages)

	#Is anything in the scan queue?
	if h_all.filter(status='QUEUED') or h_all.filter(status='RUNNING'):
		warning = 'At least one record is in the queue to be scanned, or is actively running.  Data may be stale until this completes.'
	else:
		warning = None

	context = {
		'q_result_grade' : q_grade, 
		'q_result_all' : hosts, 
		'account_list' : a_all, 
		'p_account_id' : int(selected_account_id), 
		'p_grade' : selected_grade,
		'p_sig' : selected_sig,
		'p_rc4' : selected_rc4,
		'account_name': account_name, 
		'last_update': last_update, 
		'num_pages': range(h_all_paginator.num_pages), 
		'q_result_sig_alg': q_sig_alg,
		'q_result_rc4' : q_rc4,
		'warning' : warning
	}

	return render(request, 'ssllabs/dashboard.html', context)

@login_required
def managehost(request, host_id = '0'):

	#Get list of accounts
	account_list = Account.objects.all().order_by('name')

	#Add/Edit
	if request.POST:
		hostname = request.POST['hostname']
		account_id = request.POST['account']

		if host_id == '0':
			host_detail = { 'host_id': '0', 'host':hostname, 'account_id_id': int(account_id)}
		else:
			host_detail = get_object_or_404(Host, pk=host_id);

		if hostname == '':
			return render(request, "ssllabs/manage_host.html", {'h': host_detail, 'acc': account_list, 'error_message': "Error: Hostname cannot be blank"})


		#Get list of hostnames
		hostnames = hostname.split(" ")


		#Do all of the hostnames resolve?  If not, then throw and error and don't add anything
		error = False
		for this_hostname in hostnames:
			th = this_hostname.lower().strip()
			try:
				ip = socket.gethostbyname(this_hostname)
			except socket.error as e:
				error = True
				messages.error(request, "Error for "+this_hostname+" : "+e.strerror+".  No hostnames were added.")

		if error:
			return render(request, "ssllabs/manage_host.html", {'h': host_detail, 'acc': account_list})

		for this_hostname in hostnames:

			#Strip and lower
			th = this_hostname.lower().strip()

			#If stripping whitespaces results in no host, continue to next one
			if not th:
				continue

			#Add new record
			host_detail = Host(host=th, account_id=Account(account_id=account_id), status="QUEUED", statusMessage='QUEUED')
			
			#Insert or Update record
			error = False
			try:
				host_detail.save()
				messages.success(request, th+": Hostname Successfully Saved")
			except IntegrityError as e:
				messages.error(request, th+": Hostname Already Exists")
				error = True

			except Error as e:
				error = True
				messages.error(request, th+": "+str(e))
		
		# If an error occured, go back to manage page
		if error:
			host_detail.host = request.POST['hostname']
			return render(request, "ssllabs/manage_host.html", {'h': host_detail, 'acc': account_list})
		
		return HttpResponseRedirect(reverse('ssllabs:listhosts'))

	#Adding a new host
	#Empty object
	
	host_detail = { 'host_id': '0', 'host':''}
		
	context = {'h': host_detail, 'acc': account_list}
	
	return render(request, 'ssllabs/manage_host.html', context)	

@login_required
def scanhost(request, host_id):
	host_detail = get_object_or_404(Host, pk=host_id)
	host_detail.status = "QUEUED"
	host_detail.statusMessage = "QUEUED"
	host_detail.startTime = None
	host_detail.endTime = None
	host_detail.save()

	#Make Qualys API call
	#try:
	#except: 
	
	messages.success(request, "\""+host_detail.host+"\" Successfully Queued for Scan")
	return HttpResponseRedirect(reverse('ssllabs:listhosts'))

@login_required
def deletehost(request, host_id):
	h = get_object_or_404(Host, pk=host_id)
	
	h.delete()

	messages.success(request, "\""+h.host+"\" Successfully Deleted")

	return HttpResponseRedirect(reverse('ssllabs:listhosts'))	

@login_required
def export_to_csv(request, hosts):
	response = HttpResponse(content_type='text/csv')
	response['Content-Disposition'] = 'attachment; filename="qualys_dashboard.csv"'
	
	writer = csv.writer(response)
	writer.writerow(['Account', 'Hostname', 'Port', 'Status', 'Status Message', 'Start Time', 'End Time', 'IP Address', 'Grade', 'Grade (Trust Ignored)', 'Signature Algorithm', 'Supports RC4', 'Not Before', 'Not After'])
	for h in hosts:
		writer.writerow([h.account_id, h.host, h.port, h.status, h.statusMessage, h.startTime, h.endTime, h.ipAddress, h.grade, h.gradeTrustIgnored, h.signatureAlg, h.supportsRC4, h.notBefore, h.notAfter])
		
	return response

class IndexView(generic.ListView):
	template_name = 'ssllabs/list_hosts.html'
	context_object_name = 'host_list'

	#def get_context_data(self, **kwargs):
		#context = super(IndexView, self).get_context_data(**kwargs)
		#context['account_list'] = Account.objects.order_by('name')
		#context['profile_list'] = Profile.objects.order_by('profileName')
		#return context
    
	def get_queryset(self):
		return Host.objects.order_by('host')

@login_required
class DetailView(generic.DetailView):
    model = Host
    context_object_name = 'host_detail'
    template_name = 'ssllabs/detail.html'

ssllabs/templates/ssllabs/add_multiple_hosts.html
<!DOCTYPE html>
<html>
    {% include "ssllabs/bootstrap.html" %}
    <body>
    	{% include "ssllabs/nav.html" %}


		<div class="container-fluid">
			{% if message %}<p><strong>{{ message }}</strong></p>{% endif %}
			<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
				<h1 class="page-header">Manage Hostname</h1>

				<a href="{% url 'ssllabs:listhosts' %}">Return</a>
				{% if error_message %}
				<div class="alert alert-danger" role="alert">
					<strong>{{ error_message }}</strong>
				</div>
				{% endif %}
				
				<form class="form-inline" action="{% url 'ssllabs:managehost' h.host_id %}" method="post">
					{% csrf_token %}
					<div class="form-group">
						<label for="InputHostname">Account</label>
						<select name="account" id="account">
						{% for a in acc %}
							<option value="{{a.account_id}}" {% if h.account_id_id == a.account_id %} selected {% endif %}>{{a.name}}</option>
						{% endfor %}
						</select>
					</div>
					<div class="form-group">
						<label for="InputHostname">Hostname</label>
						<input type="text" name="hostname" id="hostname" value="{{ h.host }}" size="30" />
					</div>
					<button type="submit" class="btn btn-primary">Submit</button>
				</form>
			</div>
        </div>
    </body>
</html>

ssllabs/templates/ssllabs/auth.html
<!DOCTYPE html>
<html>
    {% load staticfiles %}
    
    {% include "ssllabs/bootstrap.html" %}
    <body>
    	{% include "ssllabs/nav.html" %}

    	<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<h1 class="page-header">Login</h1>
	     	<div class="row placeholders">
	        	<div>
      				{% if error %}<div class="alert alert-danger" role="alert">{{error}}</div>{% endif %}
					<form method="post" action="{% url 'ssllabs:auth' %}" name="authForm" id="authForm">
						{% csrf_token %}
						<div class="form-group">
							<label for="InputUsername">Username</label>
							<input type="text" name="username" id="username" value="" size="30" />
						</div>
						<div class="form-group">
							<label for="InputPassword">Password</label>
							<input type="password" name="password" id="password" value="" size="30" />
						</div>
						<button type="submit" class="btn btn-primary">Submit</button>
						<input type="hidden" name="next" id="next" value="{{nexturl}}" />
					</form>
				</div>
			</div>
		</div>
        {% include "ssllabs/bootstrap_footer.html" %}
    </body>
</html>

ssllabs/templates/ssllabs/bootstrap.html
    <head>
        {% load staticfiles %}

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Akamai SSL</title>
        <!-- Latest compiled and minified CSS -->

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

        <!-- Custom CSS for Dashboard -->

        <link rel="stylesheet" href="{% static 'ssllabs/styles/dashboard.css'%}">

    </head>

ssllabs/templates/ssllabs/bootstrap_footer.html
		{% load staticfiles %}

        <!-- Latest compiled and minified JavaScript -->
        <script src="{% static 'ssllabs/scripts/jquery-2.1.3.min.js'%}"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

ssllabs/templates/ssllabs/detail.html
<!DOCTYPE html>
<html>
    {% include "ssllabs/bootstrap.html" %}
    <body>
    	{% include "ssllabs/nav.html" %}
        <div class="container-fluid">
        	<a href="{% url 'ssllabs:listhosts' %}">Return</a>
			{% if host_detail %}
			<div class="row">
				<div class="col-sm-6">
					<table class="table table-striped">
		            <tbody>
		            	<tr><th scope="row">Account</th><td>{{ host_detail.account_id }}</td></tr>
				    	<tr><th scope="row">Hostname</th><td>{{ host_detail.host }}</td></tr>
				    	<tr><th scope="row">Port</th><td>{{ host_detail.port }}</td></tr>
				        <tr><th scope="row">Grade</th><td>{{ host_detail.grade }}</td></tr>
				        <tr><th scope="row">Last Run</th><td>{{ host_detail.endTime }}</td></tr>
				    </tbody>
				</div>
			</div>
			{% else %}
			<div class="alert alert-danger" role="alert">
				<strong>No details are available for this host.</strong>  Was it deleted?
			</div>
			{% endif %}
        </div>
    </body>
</html>






    

ssllabs/templates/ssllabs/hosts.html
<a href="../" >Return</a>

{% if host_detail %}
    <table border=1>
    	<tr><td>{{ host_detail.host }}</td></tr>
    	<tr><td>{{ host_detail.port }}</td></tr>
        <tr><td>{{ host_detail.grade }}</td></tr>
        <tr><td>{{ host_detail.endTime }}</td></tr>
    </table>
{% else %}
    <p>No details are available for this host.  Was it deleted?</p>
{% endif %}

ssllabs/templates/ssllabs/index.html
<!DOCTYPE html>
<html>
    {% load staticfiles %}
    <script src="{% static 'ssllabs/scripts/Chart.min.js'%}"></script>
    {% include "ssllabs/bootstrap.html" %}
    <body>
    	{% include "ssllabs/nav.html" %}
        <div class="container-fluid">
            {% if message %}<p><strong>{{ message }}</strong></p>{% endif %}
			<div class="row">
				<div class="col-sm-6">
					{% if messages %}
	            		{% for message in messages %}
	            		<div class="alert alert-success" role="alert">
        					<strong>{{ message }}</strong>
      					</div>
	            		{% endfor %}
	          		{% endif %} 

					<table class="table table-striped">
		            <thead>
		              <tr>
		                <th>Account</th>
		                <th>Host Name</th>
		                <th>Grade</th>
		                <th>Last Run</th>
		                <th>Actions</th>
		              </tr>
		            </thead>
		            <tbody>
					{% for h in host_list %}
		        	<tr>
		        		<td>{{ h.account_id }}</td>
		        		<td>{{ h.host }}</td>
		        		<td>{{ h.grade }}</td>
		        		<td>{{ h.endTime }}</td>
		        		<td>
							<button type="button" class="btn btn-xs btn-info" id="DetailHost{{h.host_id}}" onclick="location.href='{% url 'ssllabs:detail' h.host_id %}'">Details</button>
							<button type="button" class="btn btn-xs btn-primary" id="EditHost{{h.host_id}}" onclick="location.href='{% url 'ssllabs:manage' h.host_id %}'"/>Edit</button>
					</tr>
					{% endfor %}
				</div>
			</div>
        </div>
        <canvas id="myChart" width="600" height="400"></canvas>

        <script>

var ctx = document.getElementById("myChart").getContext("2d");

var data = [
    {
        value: 300,
        color:"#F7464A",
        highlight: "#FF5A5E",
        label: "Red"
    },
    {
        value: 50,
        color: "#46BFBD",
        highlight: "#5AD3D1",
        label: "Green"
    },
    {
        value: 100,
        color: "#FDB45C",
        highlight: "#FFC870",
        label: "Yellow"
    }
]

var myDoughnutChart = new Chart(ctx).Doughnut(data);


        </script>
    </body>
</html>

ssllabs/templates/ssllabs/list_hosts.html
<!DOCTYPE html>
<html>
    {% load staticfiles %}
    <script src="{% static 'ssllabs/scripts/Chart.min.js'%}"></script>
    {% include "ssllabs/bootstrap.html" %}
    <body>
    	{% include "ssllabs/nav.html" %}
        <div class="container-fluid">
            {% if message %}<p><strong>{{ message }}</strong></p>{% endif %}
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
              <h1 class="page-header">Manage</h1>
			    {% if messages %}
            		{% for message in messages %}

                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <div class="alert alert-danger" role="alert">
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    <div class="alert alert-success" role="alert">
                    {% endif %}
                        <strong>{{ message }}</strong>
                    </div>
            		{% endfor %}
          		{% endif %} 
                <button type="button" class="btn btn-primary" id="addhost" onclick="location.href='{% url 'ssllabs:managehost' %}'">Add</button>
                <div class="table-responsive">
					<table class="table table-striped">
    		            <thead>
    		              <thead>
    		                <th>Account</th>
    		                <th>Host Name</th>
    		                <th>Grade</th>
                            <th>Status</th>
    		                <th>Last Run</th>
    		                <th>Actions</th>
    		              </tr>
    		            </thead>
    		            <tbody>
    					{% for h in host_list %}
    		        	<tr>
    		        		<td>{{ h.account_id }}</td>
    		        		<td>{{ h.host }}</td>
    		        		<td>{{ h.grade }}</td>
                            <td>{{ h.status }}</td>
    		        		<td>{{ h.endTime }}</td>
    		        		<td>
                                <button type="button" class="btn btn-xs btn-primary" id="QueueHost{{h.host_id}}" onclick="location.href='{% url 'ssllabs:scanhost' h.host_id %}'"/>Scan</button>
                                <button type="button" class="btn btn-xs btn-primary" id="DeleteHost{{h.host_id}}" onclick="location.href='{% url 'ssllabs:deletehost' h.host_id %}'"/>Delete</button>
                            </td>
    					</tr>
    					{% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>

ssllabs/templates/ssllabs/manage_host.html
<!DOCTYPE html>
<html>
    {% include "ssllabs/bootstrap.html" %}
    <body>
    	{% include "ssllabs/nav.html" %}


		<div class="container-fluid">
			<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
				<h1 class="page-header">Manage Hostname</h1>

				<a href="{% url 'ssllabs:listhosts' %}">Return</a>
				{% if messages %}
				{% for message in messages %}
				{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
				<div class="alert alert-danger" role="alert">
				{% else %}
				<div class="alert alert-success" role="alert">
				{% endif %}
				
					<strong>{{ message }}</strong>
				</div>

				{% endfor %}
				{% endif %}
				
				<form class="form-inline" action="{% url 'ssllabs:managehost' %}" method="post">
					{% csrf_token %}
					<div class="form-group">
						<label for="InputHostname">Account</label>
						<select name="account" id="account">
						{% for a in acc %}
							<option value="{{a.account_id}}" {% if h.account_id_id == a.account_id %} selected {% endif %}>{{a.name}}</option>
						{% endfor %}
						</select>
					</div>
					<div class="form-group">
						<label for="InputHostname">Hostname(s)</label>
						<input type="text" name="hostname" id="hostname" value="{{ h.host }}" size="30" />
					</div>
					<button type="submit" class="btn btn-primary">Submit</button>
				</form>
			</div>
        </div>
    </body>
</html>

ssllabs/templates/ssllabs/nav.html
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Akamai SSL</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}<li><a href="{% url 'ssllabs:logout_view' %}" >Logout</a></li> {% endif %}
            <li><a href="/admin" target="_blank">Admin</a></li>
            <li><a href="#">Help</a></li>
          </ul>
          
        </div>
      </div>
    </nav>
    <div class="container-fluid">
		<div class="row">
			<div class="col-sm-3 col-md-2 sidebar">
        {% if user.is_authenticated %}
				<ul class="nav nav-sidebar">
					<li {% if request.path == '/ssllabs/' %} class="active" {% endif %}><a href="/ssllabs/">Overview<span class="sr-only">(current)</span></a></li>
					<li {% if '/manage/' in request.path %} class="active" {% endif %}><a href="/ssllabs/manage">Manage</a></li>
				</ul>
        {% endif %}
			</div>
		</div>
	</div>